server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

spring:
  application:
    name: message
  activemq:
         broker-url: tcp://localhost:61616
         in-memory: true
         pool:
            enabled: false
         jms:
            pub-sub-domain: false


  mail:
      host: smtp.163.com
      username: devin_8_20@163.com
      password: xx18720919202
      enable:  true
      smtp:
        auth: true
      starttls:
        enable: true
        required: true
messages:
  queue: mail_queue


